from modules.autoclicker import thread_lclick, thread_rclick
from modules.movement import thread_autosprint, thread_wtap, thread_strafing
from modules.misc import thread_antiafk, selfdestruct
from modules.settings import thread_window, thread_menu, controls
from config.categories import ModuleCategory as MC

modules = {
    "LeftClicker": {
        "name": "LeftClicker",
        "category": MC.COMBAT,
        "hotkey": True,
        "toggle": True,
        "slider": 3,
        "slider_min1": 1,
        "slider_max1": 40,
        "slider_text1": "CPS:",
        "slider_step1": 1,
        "slider_default1": 20,
        "slider_min2": 0,
        "slider_max2": 10,
        "slider_text2": "Randomize:",
        "slider_step2": 1,
        "slider_default2": 2,
        "slider_min3": 0,
        "slider_max3": 10,
        "slider_text3": "Shake:",
        "slider_step3": 1,
        "slider_default3": 2,
        "checkbox": 2,
        "checkbox_text1": "Hold Leftclick",
        "checkbox_text2": "Blockhit",
        "params": ["get_slider_value", "get_slider_value", "get_slider_value", "get_checkbox_value", "get_checkbox_value"], 
        "command": thread_lclick
    },
    "RightClicker": {
        "name": "RightClicker",
        "category": MC.COMBAT,
        "hotkey": True,
        "toggle": True,
        "slider": 3,
        "slider_min1": 1,
        "slider_max1": 40,
        "slider_text1": "CPS:",
        "slider_step1": 1,
        "slider_default1": 15,
        "slider_min2": 0,
        "slider_max2": 10,
        "slider_text2": "Randomize:",
        "slider_step2": 1,
        "slider_default2": 2,
        "slider_min3": 0,
        "slider_max3": 10,
        "slider_text3": "Shake:",
        "slider_step3": 1,
        "slider_default3": 2,
        "checkbox": 1,
        "checkbox_text1": "Hold Rightclick",
        "params": ["get_slider_value", "get_slider_value", "get_slider_value", "get_checkbox_value"], 
        "command": thread_rclick
    },
    "AutoSprint": {
        "name": "AutoSprint",
        "category": MC.MOTION,
        "hotkey": True,
        "toggle": True,
        "params": [],
        "command": thread_autosprint
    },
    "W-Tap": {
        "name": "W-Tap",
        "category": MC.MOTION,
        "hotkey": True,
        "toggle": True,
        "slider": 3,
        "slider_min1": 0.01,
        "slider_max1": 1,
        "slider_text1": "Delay:",
        "slider_step1": 0.01,
        "slider_default1": 0.25,
        "slider_min2": 0.00,
        "slider_max2": 0.20,
        "slider_text2": "Randomize:",
        "slider_step2": 0.01,
        "slider_default2": 0.10,
        "slider_min3": 0.00,
        "slider_max3": 0.50,
        "slider_text3": "Hold:",
        "slider_step3": 0.01,
        "slider_default3": 0.15,
        "params": ["get_slider_value", "get_slider_value", "get_slider_value"], 
        "command": thread_wtap
    },
    "Strafing": {
        "name": "Strafing",
        "category": MC.MOTION,
        "hotkey": True,
        "toggle": True,
        "slider": 3,
        "slider_min1": 0.01,
        "slider_max1": 1,
        "slider_text1": "Delay:",
        "slider_step1": 0.01,
        "slider_default1": 0.25,
        "slider_min2": 0.00,
        "slider_max2": 0.20,
        "slider_text2": "Randomize:",
        "slider_step2": 0.01,
        "slider_default2": 0.10,
        "slider_min3": 0.00,
        "slider_max3": 0.50,
        "slider_text3": "Hold:",
        "slider_step3": 0.01,
        "slider_default3": 0.15,
        "params": ["get_slider_value", "get_slider_value", "get_slider_value"], 
        "command": thread_strafing
    },
    "AntiAFK": {
        "name": "AntiAFK",
        "category": MC.MISC,
        "hotkey": True,
        "toggle": True,
        "slider": 2,
        "slider_min1": 1,
        "slider_max1": 120,
        "slider_text1": "Timer:",
        "slider_default1": 60,
        "slider_min2": 1,
        "slider_max2": 20,
        "slider_text2": "Randomize:",
        "slider_default2": 10,
        "params": ["get_slider_value", "get_slider_value"],
        "command": thread_antiafk
    },
    "SelfDestruct": {
        "name": "SelfDestruct",
        "category": MC.MISC,
        "hotkey": True,
        "toggle": True,
        "params": [],
        "command": selfdestruct
    },
    "ActiveWindow": {
        "name": "Active Window",
        "category": MC.SETTINGS,
        "hotkey": True,
        "toggle": True,
        "label": 1,
        "label_text1": "If the active window is not Minecraft, the modules will be paused.",
        "params": [],
        "command": thread_window
    },
    "PauseInMenu": {
        "name": "Pause Menu",
        "category": MC.SETTINGS,
        "hotkey": True,
        "toggle": True,
        "label": 1,
        "label_text1": "If you are in the inventory or game menu, the modules will be paused.",
        "params": [],
        "command": thread_menu
    },
    #"Controls": {
    #    "name": "Controls",
    #    "category": MC.SETTINGS,
    #    "hotkey": False,
    #    "toggle": False,
    #    "label": 1,
    #    "label_text1": "Change to your corresponding keys in minecraft, so the program will work correctly.",
    #    "button": 5,
    #    "button1": {"button_text": "Sprint", "value": "[SHIFT_L]"},
    #    "button2": {"button_text": "Forward", "value": "[W]"},
    #    "button3": {"button_text": "Left", "value": "[A]"},
    #    "button4": {"button_text": "Backward", "value": "[S]"},
    #    "button5": {"button_text": "Right", "value": "[D]"},
    #    "params": [],
    #    "command": controls
    #}
}