# Colors
MENU_COLOR = "#1E1E1E"
CONTENT_COLOR = "#121212"
FEATURE_COLOR = "#8A2BE2"
ERROR_COLOR = "#FF0000"
GOOD_COLOR = "#017301"
FONT_COLOR = "#ffffff"
PRESS_COLOR = "#333333"

# Window Size
MIN_SIZE_W = "900"
MIN_SIZE_H = "600"
WINDOW_SIZE = f"{MIN_SIZE_W}x{MIN_SIZE_H}"

# Text & Font
FONT = "Fixedsys"          
FONT_SIZE_CONTENT = 8
FONT_SIZE_OPTIONS = 8
FONT_SIZE_SUBTITLE = 10
FONT_SIZE_TITLE = 12

# Others
CONTENT_PAD_Y = 10
CONTENT_PAD_X = 10
RELIEF_BASIC = "flat"
RELIEF_FANCY = "ridge"
RELIEF_FRAME = "sunken"
WIDTH = 20
LENGTH = 175